In [1]:
import pandas as pd

In [2]:
clientes = pd.read_csv('../data/clientes.csv')
clientes.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2436 entries, 0 to 2435
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   idCliente      2436 non-null   object
 1   flEmail        2436 non-null   int64
 2   flTwitch       2436 non-null   int64
 3   flYouTube      2436 non-null   int64
 4   flBlueSky      2436 non-null   int64
 5   flInstagram    2436 non-null   int64
 6   qtdePontos     2436 non-null   int64
 7   dtCriacao      834 non-null    object
 8   dtAtualizacao  834 non-null    object
dtypes: int64(6), object(3)
memory usage: 566.0 KB

In [3]:
clientes.sample(10)

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,dtCriacao,dtAtualizacao
2383,f8b53480-3dd5-4961-84a6-4e1967f5aa81,0,0,0,0,0,52,NaN,NaN
872,59f15851-f065-4a54-ad77-261961cb61e9,0,0,0,0,0,65,NaN,NaN
385,23cb2267-4be6-4439-b4a6-dc2cf3e5f30b,0,0,0,0,0,975,NaN,NaN
2384,f8b5c3c6-8c29-4dba-86da-abb193814fce,1,0,0,0,0,50,NaN,NaN
1141,78616e5c-6326-4d86-8436-3ee940ef95bd,0,0,0,0,0,156,NaN,NaN
1624,a829017f-dd24-40db-92de-1e632cac34c1,0,0,0,0,0,50,NaN,NaN
1865,c18cd53e-ef78-4c68-b21e-fc4559310439,0,0,0,0,0,55,NaN,NaN
622,3cbef103-2b6a-4ee3-90ac-7b0d6c3f15ca,0,0,0,0,0,50,NaN,NaN
1313,874906c8-7c13-408c-9ce9-049ac6d9a60c,0,0,0,0,0,101,NaN,NaN
599,3a542eca-5e52-48ed-b1f6-2e7088eca4f6,0,1,0,0,0,1063,0000-00-00 00:00:00.000,2025-02-10 11:01:08.798

In [8]:
# Definindo um filtro
filtro = clientes['qtdePontos'] == 0

# Criando um novo dataFrame a partir do filtro
clientes_zero_pontos = clientes[filtro]
clientes_zero_pontos

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,dtCriacao,dtAtualizacao
4,00684343-40b5-4ce7-b2e8-71a5340973bf,0,0,0,0,0,0,NaN,NaN
7,00c26486-33e8-4af9-8e0f-4ee220252ca9,0,0,0,0,0,0,NaN,NaN
31,031f1b88-5440-45af-8fa9-1423a0a15145,0,0,0,0,0,0,NaN,NaN
40,03a59296-ca4e-4521-b7a1-4c6b8a604c17,0,1,0,0,0,0,2024-11-08 13:05:31.131,2024-11-08 13:05:31.131
79,06cd7d0d-d65f-4fba-b871-541e02dd8427,0,0,0,0,0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2346,f46b7c0a-f576-469f-97c1-3cd681a72861,0,0,0,0,0,0,NaN,NaN
2354,f56cccc5-fe3f-494d-8d80-d949e1f2c0e5,0,0,0,0,0,0,NaN,NaN
2400,faf46096-5f3c-4419-befb-7365c881d2d6,0,0,0,0,0,0,NaN,NaN
2403,fb3a4cb0-1705-4456-95b9-2b7062670ba6,0,1,0,0,0,0,2025-02-28 12:17:10.398,2025-02-28 12:17:10.398
2419,fcfde021-715d-4977-9bc5-9131e5394d05,0,0,0,0,0,0,NaN,NaN

In [ ]:
# A value is trying to be set on a copy of a slice from a DataFrame.
# Um filtro não retorna uma cópia de um dataframe 
# Isso é o que chamamos de uma View -> consulta 

clientes_zero_pontos['flag_01'] = 1

/tmp/ipykernel_5879/763631690.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clientes_zero_pontos['flag_01'] = 1